### ISSUE TITLE
Cek Lab

### ISSUE THREAD

**Issue by alexwawo** [patriciafiona/project_se#1]
Cek lab bisa pilih tanggal.
jenis file gambar dan document

**Comment by patriciafiona** [comment]
Sudah diperbaiki

**Comment by alexwawo** [comment]
- Update Cek Lab belum bisa untuk jenis file selain gambar.
- Rekomendasi dari dokter bisa dikosongkan.
- Field dokter, menggunakan combo box, tapi bisa dikosongkan pilihannya. (Kalau bisa pakai plugin Select2).

**Comment by alexwawo** [comment]
- Icon file type: ukuran diperkecil (max:50px).
- Field dokter, menggunakan combo box, tapi bisa dikosongkan pilihannya. (Kalau bisa pakai plugin Select2).
